version: '2'
services:
  web:
    image: 'nginx'
    restart: always
    volumes:
      - ./web:/etc/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '8801:80'
    external_links:
      - php:php
  php:
    image: 'php:7.4-fpm'
    restart: always
    volumes:
      - ./web:/etc/nginx/html
